# DeFi Hot Wallet Configuration
# Production-ready configuration template

[server]
host = "127.0.0.1"
port = 8080
tls_enabled = false
# cert_path = "/app/keys/server.crt"
# key_path = "/app/keys/server.key"

[security]
quantum_safe_default = true
multi_sig_threshold = 2
hsm_enabled = false
encryption_algorithm = "Kyber1024"
key_derivation_rounds = 100000
session_timeout_minutes = 30

[blockchain]
default_gas_limit = 21000
transaction_timeout_seconds = 300

[blockchain.networks.eth]
rpc_url = "https://mainnet.infura.io/v3/YOUR-PROJECT-ID"
chain_id = 1
explorer_url = "https://etherscan.io"
native_token = "ETH"

[blockchain.networks.sepolia]
rpc_url = "https://sepolia.infura.io/v3/YOUR-PROJECT-ID"
chain_id = 11155111
explorer_url = "https://sepolia.etherscan.io"
native_token = "ETH"

[blockchain.networks.polygon]
rpc_url = "https://polygon-rpc.com"
chain_id = 137
explorer_url = "https://polygonscan.com"
native_token = "MATIC"

[blockchain.networks.bsc]
rpc_url = "https://bsc-dataseed.binance.org"
chain_id = 56
explorer_url = "https://bscscan.com"
native_token = "BNB"

[blockchain.networks.solana]
rpc_url = "https://api.mainnet-beta.solana.com"
explorer_url = "https://explorer.solana.com"
native_token = "SOL"

[blockchain.networks."solana-devnet"]
rpc_url = "https://api.devnet.solana.com"
explorer_url = "https://explorer.solana.com/?cluster=devnet"
native_token = "SOL"

[storage]
database_url = "sqlite:./wallet.db"
encryption_key_path = "./keys/master.key"
backup_enabled = true
backup_interval_hours = 24

[monitoring]
metrics_enabled = true
metrics_port = 9090
log_level = "info"
# alert_webhook_url = "https://your-webhook.example.com/alerts"

[i18n]
default_language = "en"
supported_languages = ["en", "zh"]
resources_path = "./resources/i18n"