name: Merge Conflict Check

on:
  pull_request:
    branches: [ main ]

jobs:
  conflict-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for merge conflicts
        run: |
          git fetch origin main
          git merge --no-commit --no-ff origin/main || {
            echo '::error ::Merge conflict detected with main branch.'
            exit 1
          }
