name: Merge Conflict Check

on:
  pull_request:
    branches: [ master ]

jobs:
  conflict-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for merge conflicts
        run: |
          git fetch origin master
          git merge --no-commit --no-ff origin/master || {
            echo '::error ::Merge conflict detected with master branch.'
            exit 1
          }
