name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install cargo tools
        run: |
          rustup component add rustfmt clippy
          cargo install cargo-audit cargo-outdated cargo-tarpaulin
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Audit dependencies
        run: cargo audit --deny warnings
      - name: Check outdated dependencies
        run: cargo outdated || true
      - name: Run tests
        run: cargo test --all
      - name: Coverage (tarpaulin)
        run: |
          cargo tarpaulin --out Xml
        continue-on-error: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
        continue-on-error: true
